export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const GET_LOGIN_LOADING = "GET_LOGIN_LOADING";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

export const GET_SIGNUP_LOADING = "GET_SIGNUP_LOADING";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_ERROR = "GET_SIGNUP_ERROR";

export const POST_DATA_LOADING = "POST_DATA_LOADING";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";

export const GET_SEARCH_LOADING = "GET_SEARCH_LOADING";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_ERROR = "GET_SEARCH_ERROR";

export const SET_EDIT_LOADING = "SET_EDIT_LOADING";
export const SET_EDIT_SUCCESS = "SET_EDIT_SUCCESS";
export const SET_EDIT_ERROR = "SET_EDIT_ERROR";

export const SET_DELETE_LOADING = "SET_DELETE_LOADING";
export const SET_DELETE_SUCCESS = "SET_DELETE_SUCCESS";
export const SET_DELETE_ERROR = "SET_DELETE_ERROR";

export const LOGOUT = "LOGOUT";

export const SORTING = "SORTING";
